#开发环境
server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://106.14.246.27:3306/db_spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/db_soft1921?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

    username: root
    password: kobe24
#    password: 00000000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#     ddl-auto：定义数据表的生成策略。update：更新或者创建数据表结构
      ddl-auto: update
#      控制台显示sql语句
    show-sql: true