spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.potato.boot.mybatis.domain
  configuration:
    map-underscore-to-camel-case: true
