spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
